In [1]:
import numpy as np
import time

In [3]:
x = np.random.random(100000000)

In [7]:
# plain python
start = time.time()
sum(x) / len(x)
print(time.time() - start)

12.475827693939209


In [8]:
# numpy
start = time.time()
np.mean(x)
print(time.time() - start)

0.043814659118652344


In [10]:
x = np.array([1,2,3,4,5])
print("x = ", x)
print()

# info about x
print("x has dimensions:", x.shape)
print("x is an object of type:", type(x))
print("The elements in x are of type:", x.dtype)

x =  [1 2 3 4 5]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [13]:
w = np.array(["Hello", "hapless", "programmer"])
print("w = ", w)
print()

# info about w
print("w has dimensions:", w.shape)
print("w is an object of type:", type(w))
print("The elements in w are of type:", w.dtype)

w =  ['Hello' 'hapless' 'programmer']

w has dimensions: (3,)
w is an object of type: <class 'numpy.ndarray'>
The elements in w are of type: <U10


In [15]:
# create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions (rows & cols):', Y.shape) # rows & columns
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions (rows & cols): (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [24]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

In [25]:
g = np.load('my_array.npy')

print()
print('g = ', g)
print()

print('g is an object of type:', type(g))
print('The elements in g are of type:', g.dtype)


g =  [1 2 3 4 5]

g is an object of type: <class 'numpy.ndarray'>
The elements in g are of type: int64


In [28]:
# create numpy array of letters a-j

# ord - given a string representing a Unicode character, returns an integer 
# representing the Unicode of that character. 
# the inverse of chr.
letter_array = [chr(x) for x in range(ord('a'), ord('j') + 1)] 
letter_array = np.array(letter_array)

print("Letter Array: ", letter_array)

# get dtype of array
print('The elements in letter_array are of type:', letter_array.dtype)

# get shape of array
print('letter_array has dimensions (rows & cols):', letter_array.shape) # rows & columns

# get size of array
print('letter_array has a total of', letter_array.size, 'elements')



Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
The elements in letter_array are of type: <U1
letter_array has dimensions (rows & cols): (10,)
letter_array has a total of 10 elements


In [35]:
# Built-in functions to create ndArrays with prefilled values

# zeros - pass in tuple indicating rows, cols
z = np.zeros((3,4))
print('\nz = np.zeros((3,4))')
print(z)

# ones
z = np.ones((2,3))
print('\nz = np.ones((2,3))')
print(z)

# full - shape, plus constant value
z = np.full((2,3), 7)
print('\nz = np.full((2,3), 7)')
print(z)

# eye - identity matrix (linear algebra), square matrix with 1s on the diagonal
z = np.eye(4) # 4 x 4
print('\nz = np.eye(4)')
print(z)

# diag - square matrix with values on the diagonal
z = np.diag([10, 20, 30, 50])

print('\nz = np.diag([10, 20, 30, 50])')
print(z)


z = np.zeros((3,4))
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

z = np.ones((2,3))
[[1. 1. 1.]
 [1. 1. 1.]]

z = np.full((2,3), 7)
[[7 7 7]
 [7 7 7]]

z = np.eye(4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

z = np.diag([10, 20, 30, 50])
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [39]:
# More built-in functions

# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)
print(x)

# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10) # start, stop
print(x)

# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3) # start, stop, step
print(x)

# use linspace when non-linear steps are required
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10) # start, stop, N - evenly spaced numbers
print(x)


[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]
[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [45]:
# reshaping arrays
# np.reshape(ndarray, new_shape) function converts the given ndarray into the 
# specified new_shape

# important to note that the new_shape should be compatible with the number of 
# elements in the given ndarray

# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)
print('Original x = ', x)

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

# We print the reshaped x
print()
print('Reshaped x = \n', x)

# can chain together functions
Y = np.arange(9).reshape(3,3)
print()
print('Y = \n', Y)
print()

# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y = 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


X = 
 [[10 11]
 [ 9  9]
 [ 6  4]]



In [51]:
# create ndarrays with random numbers that satisfy certain statistical properties

"""
NumPy allows you create random ndarrays with numbers drawn from various probability 
distributions. The function np.random.normal(mean, standard deviation, size=shape), 
for example, creates an ndarray with the given shape that contains random numbers 
picked from a normal (Gaussian) distribution with the given mean and standard deviation. 

Let's create a 1,000 x 1,000 ndarray of random floating point numbers drawn from a 
normal distribution with a mean (average) of zero and a standard deviation of 0.1
"""

X = np.random.normal(0, 0.1, size=(10, 10))
print(X)

# print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')



[[ 2.33449685e-01 -2.29480170e-02  1.16995380e-02 -6.76603997e-02
  -1.81884558e-01  1.00166344e-01 -6.52863545e-02  6.78092936e-02
  -5.46832413e-03 -1.90055500e-02]
 [ 2.76740661e-01 -6.84213645e-02  6.11453821e-03  3.62437972e-02
   3.56777061e-02  2.10376948e-02  8.30306424e-02  1.78423984e-01
   1.77954624e-01  4.24494209e-02]
 [ 1.92272242e-01  5.83009958e-02  1.68018272e-01 -1.08274836e-02
   1.25778164e-01  4.99525059e-02  8.73667860e-02 -1.90419446e-02
  -1.91885743e-02  4.87048361e-02]
 [-3.06544931e-02  1.36821598e-01  1.17970443e-04  1.38189963e-01
  -1.51228647e-01  1.22953911e-03  7.64619668e-02  1.40940700e-01
   8.56425387e-02  1.50896403e-01]
 [ 8.60826382e-02  5.32336494e-02  8.03463039e-02  7.81810746e-02
   1.91293966e-02 -9.44815699e-02 -1.82474487e-01 -4.05922885e-02
   1.04120633e-01  4.00002774e-02]
 [-2.58049230e-02 -1.36391747e-01 -7.91165991e-02 -1.26058966e-01
  -4.57896152e-02  3.65956177e-02 -1.85789503e-02 -1.36871428e-01
  -1.07908761e-01  2.08183128e-02

In [53]:
# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2, 34, 2).reshape(4, 4)   # reshape to create a rank 2 array
print()
print('X = \n', X)
print()

Y = np.linspace(2,32,16).reshape(4,4)
print()
print('Y = \n', Y)
print()


X = 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Y = 
 [[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]



In [10]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

print('\nAccess a range in the ndarray:', x[0:2])
print('* note the above yielded another ndarray *')


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

Access a range in the ndarray: [1 2]
* note the above yielded another ndarray *


In [12]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print(X)

# modify in place
X[0,1] = 15

print()
print(X)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1 15  3]
 [ 4  5  6]
 [ 7  8  9]]


In [13]:
"""
DELETE
np.delete(ndarray, elements, axis) function. 
This function deletes the given list of elements from the given ndarray along the specified axis. 
For rank 1 ndarrays the axis keyword is not required. 
For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns
"""
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x, [0,4])

# We print x with the first and last element deleted
print()
print('Modified x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We print w
print()
print('w = \n', w)



Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]


In [14]:
"""
APPEND
We can append values to ndarrays using the np.append(ndarray, elements, axis) function. 
This function appends the given list of elements to ndarray along the specified axis

Notice that when appending rows or columns to rank 2 ndarrays the rows or columns must 
have the correct shape, so as to match the shape of the rank 2 ndarray
"""
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)



Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


In [15]:
"""
INSERT
Insert values to ndarrays using the np.insert(ndarray, index, elements, axis) function. 
This function inserts the given list of elements to ndarray right before the given index 
along the specified axis.
"""
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


In [2]:
"""
STACK
Stack on top or each other (np.vstack) or side-by-side (np.hstack)

* the shape of the ndarrays must match *
"""
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x, Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y, x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


### Slicing ndArrays

**1) ndarray[start:end]**  
**2) ndarray[start:]**  
**3) ndarray[:end]**  


The first method is used to select elements between the start and end indices. 

The second method is used to select all elements from the start index till the last index. 

The third method is used to select all elements from the first index till the end index. 

_Note that in methods one and three, the end index is excluded._ 

We should also note that since ndarrays can be multidimensional, when doing slicing you usually have to specify a slice for each dimension of the array.

In [3]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


### Slicing and Copying
It is important to note that when we _perform slices_ on ndarrays and save them into new variables, as we did above, the _data is not copied into the new variable_. This is one feature that often causes confusion for beginners. Therefore, we will look at this in a bit more detail.

In the above examples, when we make assignments, such as:

Z = X[1:4,2:5]

the slice of the original array X is not copied in the variable Z. Rather, **X and Z are now just two different names for the same ndarray**. 

We say that _slicing only creates a different view of the original array_. This means that if you make changes in Z you will be in effect changing the elements in X as well. 

**Copy**

If you want to create a new ndarray that contains a copy of the values in the slice we need to use the **np.copy()** function. The np.copy(ndarray) function creates a copy of the given ndarray. This function can also be used as a method, in the same way as we did before with the reshape function.

create a copy of the slice using the np.copy() function

Z = np.copy(X[1:4,2:5])

create a copy of the slice using the copy as a method

W = X[1:4,2:5].copy()


### Boolean Indexing, Set Operations, and Sorting

**Boolean Indexing**
Allows us to select elements using logical arguments instead of explicit indices.

X = np.arange(25).reshape(5, 5)

print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1

X[(X > 10) & (X < 17)] = -1



In [4]:
X = np.arange(25).reshape(5, 5)
print()
print('X = \n', X)
print()

print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

X[(X > 10) & (X < 17)] = -1
print()
print('X = \n', X)
print()



X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



### Set Operations

**numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)**

    Find the intersection of two arrays.

    Return the sorted, unique values that are in both of the input arrays.

**numpy.setdiff1d(ar1, ar2, assume_unique=False)**

    Find the set difference of two arrays.

    Return the unique values in ar1 that are not in ar2.

**numpy.union1d(ar1, ar2)**

    Find the union of two arrays.

    Return the unique, sorted array of values that are in either of the two input arrays.


In [11]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:: np.intersect1d(x,y):', np.intersect1d(x,y))
print('The elements that are in x that are not in y:: np.setdiff1d(x,y):', np.setdiff1d(x,y))
print('All the elements of x and y:: np.union1d(x,y):',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y:: np.intersect1d(x,y): [2 4]
The elements that are in x that are not in y:: np.setdiff1d(x,y): [1 3 5]
All the elements of x and y:: np.union1d(x,y): [1 2 3 4 5 6 7 8]


In [15]:
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26, 1).reshape(5, 5)
print()
print('X = ', X)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 == 1]
print()
print('Y = ', Y)



X =  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Y =  [ 1  3  5  7  9 11 13 15 17 19 21 23 25]
